### ISSUE TITLE
Syntax highlighting line numbering style misalignment

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#736]
When used with a "non-default" font size, the syntax highlighting line numbers become misaligned:

![screenshot 2018-10-05 at 08 35 01](https://user-images.githubusercontent.com/206834/46522084-a636b000-c879-11e8-881a-e31cb7234309.png)

Modifying the `line-height` and `font-size` in the following style appears (fsr!) to make it work in both cases:

```css
.markdown table.rouge-table td:first-child pre {
    font-style: italic;
    color: #999;
    font-size: 70%;
    line-height: 188%;
}
```

🤷‍♂️ :css:
